server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver 는 deprecated!
    hikari:
      connection-timeout: 5000
      data-source-properties:
        serverTimezone: Asia/Seoul
        characterEncoding: utf8
        useSSL: false
  jpa:                            # JPA Config
    show-sql: true
    hibernate.ddl-auto: update
    # hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  redis:                          # redis config add
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 60

logging:
#  level:                         # 잠시 꺼두려고 한다.
#    # org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace
  config: classpath:logback-local.xml
